server:
  port: 8200

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/ecommerce_stage_db
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        use_sql_comments: true
        format_sql: true
  flyway:
    enabled: false
    
logging:
  file:
    name: src/main/resources/script/stage_log.log
    clean-history-on-start: true
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web: DEBUG
        data: DEBUG
      boot:
        autoconfigure:
          data:
            rest: DEBUG
            jpa: DEBUG
            orm: DEBUG

# ----------------------------------------------------
# ACTUATOR + PROMETHEUS CONFIG
# ----------------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus   # ⚠ Solo lo necesario (seguro)
  endpoint:
    health:
      show-details: always                # Necesario para dashboards
  metrics:
    export:
      prometheus:
        enabled: true                     # ⚠ Activa /actuator/prometheus
